//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
    
        public virtual user user { internal get; set; }
    }
}
